#!/bin/sh
name=`echo $PWD | rev | cut -d / -f 1 | rev`
find . ! -path './.git/*' ! -path './build/*' -type f | xargs sed -i "s/ktor-starter/$name/g"
find . -depth -type d -name ktor-starter -execdir mv {} $name \;
rm eject
git remote rm origin
git add --all
git commit -m "ejected from ktor-starter"
