#!/bin/sh
name=`echo $PWD | rev | cut -d / -f 1 | rev`
nameSafe=`echo $name | sed 's/-/_/g'`
find . ! -path './.git/*' ! -path './build/*' -type f | xargs sed -i "s/ktor-starter/$name/g"
find . ! -path './.git/*' ! -path './build/*' -type f | xargs sed -i "s/ktor_starter/$nameSafe/g"
find . -depth -type d -name ktor_starter -execdir mv {} $nameSafe \;
rm eject
git remote rm origin
git add --all
git commit -m "ejected from ktor-starter"
