#!/bin/sh
./gradlew clean shadowJar docker dockerPush deploy
echo waiting for deployment `scripts/versionByDepth` \(currently `scripts/deployedVersion`\)
until [ `scripts/versionByDepth` == `scripts/deployedVersion` ] ; do
  sleep 1
done
echo running tests against deployment
baseUrl=`scripts/baseUrl` ./gradlew cleanTest test