#!/bin/sh
./gradlew clean shadowJar
docker build -t painkillergis/ktor-starter:`scripts/versionByDepth` .
docker push painkillergis/ktor-starter:`scripts/versionByDepth`
cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ktor-starter
  labels:
    app: ktor-starter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ktor-starter
  template:
    metadata:
      labels:
        app: ktor-starter
    spec:
      containers:
      - name: ktor-starter
        image: painkillergis/ktor-starter:`scripts/versionByDepth`
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ktor-starter
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: ktor-starter
EOF
echo waiting for deployment `scripts/versionByDepth` \(currently `scripts/deployedVersion`\)
until [ `scripts/versionByDepth` == `scripts/deployedVersion` ] ; do
  sleep 1
done
