#!/bin/sh
docker build -t painkillergis/recommendations:`scripts/versionByDepth` .
docker push painkillergis/recommendations:`scripts/versionByDepth`
cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendations
  labels:
    app: recommendations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendations
  template:
    metadata:
      labels:
        app: recommendations
    spec:
      containers:
      - name: recommendations
        image: painkillergis/recommendations:`scripts/versionByDepth`
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: recommendations
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: recommendations
EOF
echo waiting for deployment `scripts/versionByDepth` \(currently `scripts/deployedVersion`\)
until [ `scripts/versionByDepth` == `scripts/deployedVersion` ] ; do
  sleep 1
done
